### ISSUE TITLE
Workflow error PHP

### ISSUE THREAD

**Issue by DigitalGentleman** [sammichshop/alfred-campaign-url-builder#1]
Hi I switched computers and now I keep getting this message:

<img width="268" alt="Schermafbeelding 2021-12-08 om 17 01 03" src="https://user-images.githubusercontent.com/6670720/145241046-64bb815d-b078-4975-86ba-9c7e13a10142.png">

Should I install the latest PHP on my system? Can't recall I did that last time.

Love this workflow so thanks a lot for developing it :)

**Comment by joetannenbaum** [comment]
So glad you're enjoying! I would check the path of PHP on your system and then update that in the workflow. So in the terminal run:

```
which php
```

and whatever path is output, make sure that's the path that's being passed into the workflow.

**Comment by DigitalGentleman** [comment]
Fixt it by installing php via homebrew. Thanks
